### ISSUE TITLE
Setup Installation

### ISSUE THREAD

**Issue by Mikael17125** [mlvlab/SpeaQ#4]
Hi I have faced some issues, can you help me?

> Traceback (most recent call last):
  File "/home/mikael/Code/SpeaQ-main/train_iterative_model.py", line 14, in <module>
    from SpeaQ.engine import JointTransformerTrainer
ModuleNotFoundError: No module named 'SpeaQ'

I just follow the installation on your README.md and run the code

**Comment by jonghakim35** [comment]
The code should work after modifying the code directory from `/home/mikael/Code/SpeaQ-main` to `/home/mikael/Code/SpeaQ`.
