### ISSUE TITLE
A little question about the number of rel queries

### ISSUE THREAD

**Issue by zhuminghong-123** [mlvlab/SpeaQ#7]
I noticed that the default NUM_RELATION_QUERIES is set to 300, does it mean that the number of rel queries is 300 instead of 600 as described in the paper? What is the proper way to set it to 600? I get some size mismatch problem when I simply set NUM_RELATION_QUERIES to 600.

**Comment by jonghakim35** [comment]
As I remember, the options below should set the number of relation queries to 600.
You can find identical options applied for SpeaQ training scripts in README.md of this repository.

`MODEL.DETR.MULTIPLY_QUERY 2 MODEL.DETR.ONLY_PREDICATE_MULTIPLY`
